### PR TITLE
Fix building on Android by removing 'ios' prefix.

### PR DESCRIPTION
**Pull request by mjdouglas**
Building a bundle for android now fails to link react-native-progress-hud with react-native 0.24.1. This pull request fixes it by renaming the file to remove the 'ios' prefix.

### CODE REVIEW

**Comment by grabbou** [comment]
I haven't tested the Android compatibility yet to be honest - does all works well on Android for you after that change?

**Comment by mjdouglas** [comment]
Yeah, it's works well, and worked well previously. I'm guessing a recent
packager change broke it.

[Example](https://www.dropbox.com/s/madssfj4fpbgupo/react-native-progress-hud.png?dl=0).

**Comment by grabbou** [comment]
Awesome, thanks. LGTM. Will merge & wait for @naoufal to push it over to `npm`. In worst case, there are bugs on Android, but it shouldn't break anything.

**Comment by naoufal** [comment]
Just published this to npm gentlemen.  🚀 

Thanks to both of you for jumping on this so quickly.

**Pull request merged**
